### ISSUE TITLE
SQL bitwise operators: &, |, ^...

### ISSUE THREAD

**Issue by tarag** [vapor/sql-kit#134]
Since SQL bitwise operators are not supported, one must use raw SQL syntax for queries using these operators.

It would be great if we could do :

```
MyModel.query(on: app.db)
            .filter(\.$optionSet & myOption)
```

instead of

```
MyModel.query(on: app.db)
            .filter(.sql(raw: "(option_set & \(myOption) != 0"))
```

**Comment by 0xTim** [comment]
You could write this as
```swift
MyModel.query(on: app.db)
            .filter(\.$optionSet, .custom("&"), myOption)
```

**Comment by gwynne** [comment]
Additionally, this issue should be on [fluent-kit](https://github.com/vapor/fluent-kit), not sql-kit.
