### ISSUE TITLE
SQLColumnUpdateBuilder.set does not provide options to specify encoding strategies

### ISSUE THREAD

**Issue by sidepelican** [vapor/sql-kit#170]
https://github.com/vapor/sql-kit/blob/f7bbbb022cb52e1828a137bcab2bd1ea2a3e583d/Sources/SQLKit/Builders/SQLColumnUpdateBuilder.swift#L14-L16

`.set(model:)` does not provide a way to specify `SQLQueryEncoder` options.
This will be in trouble when dealing with simple Codable types (that is not Fluent type)and have optional properties.

motivation is maybe similar to https://github.com/vapor/sql-kit/pull/161 .

**Comment by gwynne** [comment]
You're in luck; I'm currently working on an SQLKit PR that will address this (among numerous other concerns).

**Comment by sidepelican** [comment]
any updates?

**Comment by gwynne** [comment]
This was addressed by #172.
