### ISSUE TITLE
INSERT INTO SELECT

### ISSUE THREAD

**Issue by CrownedPhoenix** [vapor/sql-kit#182]
It would be helpful to have support for this kind of syntax:
```
INSERT INTO table2
SELECT * FROM table1
WHERE condition;
```
I believe this is standard SQL(?)

**Comment by gwynne** [comment]
SQLKit has supported this syntax since version 3.29.0:
```swift
sqlDatabase.insert(into: "table")
.select { $0
    .column("*")
    .from("table1")
    .where(...)
}
.run()
```

**Comment by CrownedPhoenix** [comment]
Sorry about that. I had forgotten that I'm on an older version. Thanks for the reference.
