### ISSUE TITLE
Column subquery helpers

### ISSUE THREAD

**Issue by 0xTim** [vapor/sql-kit#24]
Currently, when using `SQLExpression.subquery()` with `SQLSelectBuilder`,  the result is something like this:
```swift
database
    .select()
    .column(.subquery(database.select()
        .column(.keyPath(\Foo.bar))
        .from(Foo.self)
        .where(.column(.keyPath(\Foo.id)) == .bind(value))
        .query
    )
```

Calling `database.select()` again and referring to `.query` at the end are awkward constructions; it should be possible for context to infer some of this. I'm not sure exactly what this would look like, but I'm certain it can be improved.

**Comment by tanner0101** [comment]
This is a tricky one. I'm thinking something like this might be nice:

```swift
let rows = try conn.select()
    .all()
    .column(subquery: { conn in
        return conn.select()
            .column(\Planet.id).from(Planet.self)
            .limit(1)
    }, as: .identifier("firstPlanetID"))
    .from(Galaxy.self)
    .all().wait()

let rows = try conn.select()
    .all()
    .column(subquery: { $0.raw("SELECT 1 + 1")}, as: .identifier("two"))
    .from(Galaxy.self)
    .all().wait()
```

The signature for that method would be:

```swift
public func column<B>(
    subquery closure: (Connection) -> (B),
    as alias: Connection.Query.Select.SelectExpression.Identifier? = nil
) -> Self
    where B: SQLQueryBuilder, B.Connection.Query == Connection.Query.Select.SelectExpression.Expression.Subquery
```

**Comment by tanner0101** [comment]
Also worth noting the trailing closure shorthand if you don't care to specify an alias:

```swift
let rows = try conn.select()
    .all()
    .column { $0.raw("SELECT 1 + 1") }
    .from(Galaxy.self)
    .all().wait()
```

**Comment by gwynne** [comment]
Partial subquery support was recently added by #141, additional support will be forthcoming. Closing this issue out as it refers to severely outdated syntax and behaviors.
