### ISSUE TITLE
SQL92 standard has a mandatory drop behavior that sql-kit omits

### ISSUE THREAD

**Issue by kerusan** [vapor/sql-kit#64]
`DROP TABLE IF EXISTS "planets"
`

In SQL 92, the drop behavior, either RESTRICT or CASCADE is mandatory after the table name. Some databases requires either one of them to be present in a DROP TABLE statement, and there’s no way to specify that in sql-kit.

**Comment by tanner0101** [comment]
I did some quick digging on our existing supported DBs and I see that:
- Postgres: Fully supports these options: https://www.postgresql.org/docs/9.1/sql-droptable.html
- MySQL: Accepts the syntax, but does nothing: https://dev.mysql.com/doc/refman/8.0/en/drop-table.html
- SQLite: Does not accept the syntax: https://www.sqlitetutorial.net/sqlite-drop-table/

Given we have a wide range of support here, I'd say this makes sense on `SQLDialect`. Something like:

```swift
var supportsDropTableAction: Bool { get }
```

With a default implementation of true. We could then add `var action: SQLExpression?` to `SQLDropTable` and a new methods for setting it. 

If `supportsDropTableAction` is true on a given dialect, and `SQLDropTable.action` is set, then we serialize. We can also say that if `supportsDropTableAction` is true and `SQLDropTable.action` is not set, that we always serialize the default: `RESTRICT`

**Comment by kerusan** [comment]
The standards semantic is 'DROP BEHAVIOUR', and not action. And why not use the SQLDialect here too with a `supportsDropBehaviour:` with a default implementation fo false.
( [SQL92 BNF](https://ronsavage.github.io/SQL/sql-92.bnf.html) )

**Comment by johan-carlberg** [comment]
I’ve created pull request #87 which should resolve this.
