### ISSUE TITLE
Expand SQLDataType options

### ISSUE THREAD

**Issue by kerusan** [vapor/sql-kit#65]
Code snippet
```
        try self.db.create(table: "galaxies")
            .column("id", type: .int, .primaryKey)
            .column("name", type: .text)
            .run().wait()

```

Generates SQL as

`CREATE TABLE "galaxies"("id" INTEGER PRIMARY KEY DEFAULT UNIQUE, "name" TEXT)
`

The data type TEXT is not part of SQL 92, and is not recognized by Frontbase. There needs to be some way to declare or alias to a VARCHAR or CHARACTER VARYING type.

Vapor 3 was more flexible.

(Autoincrement is implemented in Frontbase by setting the default to the UNIQUE function).

**Comment by tanner0101** [comment]
You can pass any `SQLExpression` to the `type` and `constraints` fields:

```swift
try self.db.create(table: "galaxies")
    .column("id", type: SQLRaw("INTEGER"), SQLExpression("UNIQUE"))
    .column("name", type: SQLRaw("VARCHAR"))
    .run().wait()
```

That said, maybe we could have [`SQLDataType`](https://github.com/vapor/sql-kit/blob/master/Sources/SQLKit/Query/SQLDataType.swift) integrate with `SQLDialect`. Perhaps instead of having defaults like `.int`, `.text`, etc, we have `SQLDialect` attempt to return the best possible type for a given Swift type? I'm open to ideas here.

**Comment by kerusan** [comment]
+1

**Comment by kerusan** [comment]
The +1 is for solving it with ' SQLDataType integrate with SQLDialect'

**Comment by HagvallDataAB** [comment]
+1

**Comment by johan-carlberg** [comment]
> You can pass any `SQLExpression` to the `type` and `constraints` fields:
> 
> ```swift
> try self.db.create(table: "galaxies")
>     .column("id", type: SQLRaw("INTEGER"), SQLRaw("UNIQUE"))
>     .column("name", type: SQLRaw("VARCHAR"))
>     .run().wait()
> ```

This solution does work, although it needs to be expressed as either
```swift
try self.db.create(table: "galaxies")
    .column("id", type: .custom(SQLRaw("INTEGER")), .custom(SQLRaw("UNIQUE")))
    .column("name", type: .custom(SQLRaw("VARCHAR")))
    .run().wait()
```
or
```swift
try self.db.create(table: "galaxies")
    .column(SQLRaw("id"), type: SQLRaw("INTEGER"), SQLRaw("UNIQUE"))
    .column(SQLRaw("name"), type: SQLRaw("VARCHAR"))
    .run().wait()
```

**Comment by fatto** [comment]
`SQLDataType` goes through `SQLDialect` `customDataType(for dataType: SQLDataType)` function so this issue can be closed now I think.
