### ISSUE TITLE
SQL 92 expects the default clause to come before column constraint definitions

### ISSUE THREAD

**Issue by kerusan** [vapor/sql-kit#66]
`CREATE TABLE "galaxies"("id" INTEGER PRIMARY KEY DEFAULT UNIQUE, "name" TEXT)
`

SQL 92 expects the default clause to come before column constraint definitions (PRIMARY KEY in this case). Frontbase requires the default clause to come directly after the type.

**Comment by tanner0101** [comment]
I think the other DBs that use SQLKit may support the SQL 92 ordering. We can try changing the ordering here and see if CI tests pass. If it all works, great.

If not, then we can leverage `SQLDialect` to make this ordering dynamic.

**Comment by kerusan** [comment]
Code snippet
        try self.db.create(table: "galaxies")
            .column("id", type: .int, .primaryKey)
            .column("name", type: .text)
            .run().wait()
Generates SQL as
CREATE TABLE "galaxies"("id" INTEGER PRIMARY KEY DEFAULT UNIQUE, "name" TEXT)

**Comment by tanner0101** [comment]
Ah, that's because the `SQLDialect`'s default implementation of `defaultLiteral` is confusingly `DEFAULT`. That should be overridden with whatever SQL 92's version of `AUTO_INCREMENT` or `GENERATED BY DEFAULT` is.

**Comment by johan-carlberg** [comment]
I’ve created pull request #88 which should resolve this.

**Comment by kerusan** [comment]
This is fixed and merged by pullrequest #88 so I close this.
